apiVersion: cd.coding.net/v1alpha1
kind: GitSource
metadata:
  name: team-config
spec:
  git:
    url: https://e.coding.net/bedoke/iaas/go-scaffold-svc.git
    cred: git
    ref:
      branch: master
  templateRenderer:
    engine: Orbit
    path: /go-scaffold-svc
    files:
    - values.yaml
  interval: 1m
