apiVersion: oam.coding.net/v1alpha1
kind: ComponentDefinition
metadata:
  name: DeploymentTemplate
spec:
  description: 系统内置的Deployment服务模板
  available: true
  type: SERVICE
  workload:
    kube:
      template: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{.name}}
          annotations:
            reloader.stakater.com/auto: "true"
        spec:
          {{- if .replicas }}
          replicas: {{ .replicas }}
          {{- end }}
          selector:
            matchLabels:
              app: {{.name}}
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 25%
              maxSurge: 25%
          template:
            metadata:
              labels:
                app: {{.name}}
            spec:
              containers:
              - name: {{.name}}
                image: {{ .image }}
                imagePullPolicy: IfNotPresent
                ports:
                - containerPort: {{.port}}
  service:
    kube:
      template: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: {{.name}}
        spec:
          selector:
            app: {{.name}}
          ports:
          - name: http
            port: {{.port}}
            protocol: TCP
            targetPort: {{.port}}
          type: ClusterIP
  customVariables:
  - name: args
    description: 参数
    required: false
    type: ARRAY
  - name: image
    description: 容器的镜像
    required: true
    type: IMAGE
  - name: port
    description: 端口号
    required: true
    type: INT
  - name: replicas
    description: 副本数
    required: false
    type: INT
  - name: name
    description: 服务名称
    required: true
    type: STRING
  - name: cmd
    description: 启动命令
    required: false
    type: STRING
