
data:
  redis:
    addr: 127.0.0.1:6379
    password: '123456'
    db: 2
    read_timeout: 0.2s
    write_timeout: 0.2s
  meilisearch:
    host: http://127.0.0.1:7700
    api_key: '123456'
    timeout: 0.2s