// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/beiduoke/go-scaffold/api/common/conf"
	"github.com/beiduoke/go-scaffold/app/core/service/internal/data"
	"github.com/beiduoke/go-scaffold/app/core/service/internal/server"
	"github.com/beiduoke/go-scaffold/app/core/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger, registrar registry.Registrar, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	client := data.NewEntClient(bootstrap, logger)
	redisClient := data.NewRedisClient(bootstrap, logger)
	meilisearchClient := data.NewMeilisearchClient(bootstrap, logger)
	node := data.NewSnowflake(logger)
	dataData, cleanup, err := data.NewData(logger, bootstrap, client, redisClient, meilisearchClient, node)
	if err != nil {
		return nil, nil, err
	}
	syncedEnforcer := data.NewAuthzCasbinClient(bootstrap, logger)
	authorized := data.NewAuthorized(syncedEnforcer, logger)
	authRepo := data.NewAuthRepo(dataData, authorized, logger)
	authService := service.NewAuthService(logger, authRepo)
	userRepo := data.NewUserRepo(dataData, logger)
	userService := service.NewUserService(logger, userRepo)
	roleRepo := data.NewRoleRepo(dataData, logger)
	roleService := service.NewRoleService(logger, roleRepo)
	grpcServer := server.NewGRPCServer(bootstrap, logger, authService, userService, roleService)
	app := newApp(logger, registrar, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
