// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bedoke/go-scaffold/internal/biz"
	"github.com/bedoke/go-scaffold/internal/conf"
	"github.com/bedoke/go-scaffold/internal/data"
	"github.com/bedoke/go-scaffold/internal/server"
	"github.com/bedoke/go-scaffold/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	adminRepo := data.NewAdminRepo(dataData, logger)
	adminUsecase := biz.NewAdminUsecase(adminRepo, logger)
	adminService := service.NewAdminService(adminUsecase)
	grpcServer := server.NewGRPCServer(confServer, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, adminService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
