server:
  http:
    addr: 0.0.0.0:8011
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9011
    timeout: 1s
  websocket:
    addr: 0.0.0.0:7011
    timeout: 1s
    path: /
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/go_scaffold?charset=utf8mb4&parseTime=true
    log_level: 1
  redis:
    addr: 127.0.0.1:6379
    password: '123456'
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  jwt:
    secret_key: some_jwt_sign_key
    expires_time: 864000s
    header: Authorization
    scheme: Bearer
  casbin: 
    model_path: ../../configs/casbin/model.conf
    policy_path: ../../configs/casbin/policy.csv
admin:
  super: admin