server:
  http:
    addr: 0.0.0.0:8011
    timeout: 1s
    cors:
      headers:
        - "X-Requested-With"
        - "Content-Type"
        - "Authorization"
      methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "HEAD"
        - "OPTIONS"
      origins:
        - "*"
    middleware:
      auth:
        method: "HS256"
        key: "some_api_key"
      casbin: 
        model_path: ../../configs/casbin/rbac_with_domains.conf
        policy_path: ../../configs/casbin/policy.csv
  grpc:
    addr: 0.0.0.0:9011
    timeout: 1s
    middleware:
  websocket:
    addr: 0.0.0.0:7011
    timeout: 1s
    path: /
    middleware:
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/go_scaffold?charset=utf8mb4&parseTime=true
    log_level: 1
  redis:
    addr: 127.0.0.1:6379
    password: '123456'
    read_timeout: 0.2s
    write_timeout: 0.2s
  meilisearch:
    host: http://127.0.0.1:7700
    api_key: '123456'
    timeout: 0.2s
base:
  admin:
    domain_id: 1
    user_id: 1