// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/beiduoke/go-scaffold/api/common/conf"
	"github.com/beiduoke/go-scaffold/internal/biz"
	"github.com/beiduoke/go-scaffold/internal/data"
	"github.com/beiduoke/go-scaffold/internal/server"
	"github.com/beiduoke/go-scaffold/internal/service/api"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger, registrar registry.Registrar, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	v := data.NewModelMigrate()
	db := data.NewGormClient(bootstrap, logger, v)
	client := data.NewRedisClient(bootstrap, logger)
	meilisearchClient := data.NewMeilisearchClient(bootstrap, logger)
	syncedEnforcer := data.NewAuthzCasbinClient(bootstrap, logger)
	node := data.NewSnowflake(logger)
	dataData, cleanup, err := data.NewData(bootstrap, db, client, meilisearchClient, syncedEnforcer, node, logger)
	if err != nil {
		return nil, nil, err
	}
	transaction := data.NewTransaction(dataData)
	menuRepo := data.NewMenuRepo(dataData, logger)
	domainRepo := data.NewDomainRepo(logger, dataData, menuRepo)
	deptRepo := data.NewDeptRepo(logger, dataData)
	roleRepo := data.NewRoleRepo(logger, dataData, menuRepo, deptRepo)
	authenticator := server.NewAuthenticator(bootstrap, logger)
	postRepo := data.NewPostRepo(logger, dataData)
	userRepo := data.NewUserRepo(logger, bootstrap, dataData, authenticator, domainRepo, roleRepo, postRepo, menuRepo, deptRepo)
	bizBiz := biz.NewBiz(logger, transaction, domainRepo, roleRepo, userRepo)
	authUsecase := biz.NewAuthUsecase(logger, bizBiz, authenticator)
	userUsecase := biz.NewUserUsecase(logger, bizBiz)
	domainUsecase := biz.NewDomainUsecase(logger, bizBiz)
	roleUsecase := biz.NewRoleUsecase(logger, bizBiz)
	menuUsecase := biz.NewMenuUsecase(logger, bizBiz, menuRepo)
	deptUsecase := biz.NewDeptUsecase(logger, bizBiz, deptRepo)
	postUsecase := biz.NewPostUsecase(logger, bizBiz, postRepo)
	dictRepo := data.NewDictRepo(logger, dataData)
	dictUsecase := biz.NewDictUsecase(logger, bizBiz, dictRepo)
	apiService := api.NewApiService(logger, authUsecase, userUsecase, domainUsecase, roleUsecase, menuUsecase, deptUsecase, postUsecase, dictUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, apiService, logger)
	authorized := server.NewAuthorized(syncedEnforcer, logger)
	securityUserCreator := data.NewSecurityUser(logger, dataData, userRepo)
	middleware := server.NewAuthMiddleware(authenticator, authorized, securityUserCreator)
	v2 := server.NewMiddleware(logger, middleware)
	httpServer := server.NewHTTPServer(bootstrap, logger, apiService, v2)
	app := newApp(logger, registrar, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
