apiVersion: oam.coding.net/v1alpha1
kind: Trait
metadata:
  name: annotation
  annotations:
    name: 注解
spec:
  description: 把额外的元信息打到服务注解上，用于外部系统查找或控制
  available: true
  strategy: PATCH
  targetGVK:
    apiVersion: apps/v1
    kind: Deployment
  contextVariables:
  - name: src
    description: 目标对象
    required: true
    type: STRING
  - name: namespace
    description: 目标对象命名空间
    required: true
    type: STRING
  - name: name
    description: 目标对象名称
    required: true
    type: STRING
  customVariables:
  - name: anno_key
    description: 注入到K8S对象的额外属性的键
    required: true
    type: STRING
  - name: anno_value
    description: 注入到K8S对象的额外属性的值
    required: true
    type: STRING
  traitDefinition:
    kube:
      template: |-
        #运维插件的定义
        #假设运维插件的 id 和 name 都是 annotation
        # patch 类型的插件，作用对象类型 Deployment
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{.name}}
          namespace: {{.namespace}}
          labels:
            coding.oam.trait/annotation: "true"
          annotations:
            {{.anno_key}}: {{.anno_value}}
