apiVersion: oam.coding.net/v1alpha1
kind: Trait
metadata:
  name: graceful-shutdown
  annotations:
    name: 优雅关闭
spec:
  description: |-
    K8S 会自动进行故障恢复，负载均衡。处理好优雅关闭可以在 K8S 进行容器调度操作时，减少对用户流量的影响。
    K8S 优雅关闭的流程：
    1. 摘除流量
    2. 执行 preStop hook
    3. （同时）发送 SIGTERM 给容器进程
    4. 等待“优雅关闭等待时间”
    5. 发送 SIGKILL 强行杀死容器进程
  available: true
  strategy: PATCH
  targetGVK:
    apiVersion: apps/v1
    kind: Deployment
  contextVariables:
  - name: src
    description: 目标对象
    required: true
    type: STRING
  - name: namespace
    description: 目标对象命名空间
    required: true
    type: STRING
  - name: name
    description: 目标对象名称
    required: true
    type: STRING
  customVariables:
  - name: grace_period_seconds
    description: K8S 在发送 SIGTERM 和执行 preStop Hook 后所等待的时间。等待结束后将强行杀死进程。
    required: true
    type: INT
  - name: pre_stop_hook
    description: 如果定义了 preStop Hook，K8S 在关闭容器前调用这个 Hook。注意，就算定义了 preStop hook，也要检查业务进程在收到
      SIGTERM 后的反应。
    required: false
    type: OBJECT
  traitDefinition:
    kube:
      template: |-
        #运维插件的定义
        #假设运维插件的 id 和 name 都是 graceful-shutdown
        # patch 类型的插件，作用对象类型 Deployment
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{.name}}
          namespace: {{.namespace}}
          labels:
            coding.oam.trait/graceful-shutdown: "true"
        spec:
          template:
            spec:
              terminationGracePeriodSeconds: {{.grace_period_seconds}}
              containers:
              - name: {{.name}}
                {{- if .pre_stop_hook}}
                lifecycle:
                  preStop:
                    {{- if .pre_stop_hook.http_hook}}
                    httpGet:
                      path: {{.pre_stop_hook.http_hook.path}}
                      port: {{.pre_stop_hook.http_hook.port}}
                      httpHeaders:
                      {{- range .pre_stop_hook.http_hook.headers}}
                      - name: {{.name}}
                        value: {{.value | quote}}
                      {{- end}}
                    {{- end}}
                    {{- if .pre_stop_hook.cmd_hook}}
                    exec:
                      command:
                      {{- range .pre_stop_hook.cmd_hook.cmd}}
                      - {{.}}
                      {{- end}}
                    {{- end}}
                {{- end}}
