apiVersion: oam.coding.net/v1alpha1
kind: Trait
metadata:
  name: label
  annotations:
    name: 标签
spec:
  description: 把额外的元信息打到服务标签上，用于外部系统查找或控制
  available: true
  strategy: PATCH
  targetGVK:
    apiVersion: apps/v1
    kind: Deployment
  contextVariables:
  - name: src
    description: 目标对象
    required: true
    type: STRING
  - name: namespace
    description: 目标对象命名空间
    required: true
    type: STRING
  - name: name
    description: 目标对象名称
    required: true
    type: STRING
  customVariables:
  - name: label_key
    description: 注入到K8S对象的额外标签的键，通常用于外部系统查找或控制
    required: true
    type: STRING
  - name: label_value
    description: 注入到K8S对象的额外标签的值，，通常用于外部系统查找或控制
    required: true
    type: STRING
  traitDefinition:
    kube:
      template: |-
        #运维插件的定义
        #假设运维插件的 id 和 name 都是 label
        # patch 类型的插件，作用对象类型 Deployment
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{.name}}
          namespace: {{.namespace}}
          labels:
            coding.oam.trait/label: "true"
            {{.label_key}}: {{.label_value}}
