apiVersion: oam.coding.net/v1alpha1
kind: Trait
metadata:
  name: nginx-ingress
  annotations:
    name: nginx-ingress
spec:
  description: |-
    通过 nginx 对外暴露服务。
    K8S 集群版本大于 1.19 且要求先安装 ingress-nginx-controller, 请联系集群管理员安装，或者访问 https://kubernetes.github.io/ingress-nginx/deploy/#quick-start 获取安装方式。
  available: true
  strategy: ADD
  targetGVK:
    apiVersion: v1
    kind: Service
  contextVariables:
  - name: src
    description: 目标对象
    required: true
    type: STRING
  - name: namespace
    description: 目标对象命名空间
    required: true
    type: STRING
  - name: name
    description: 目标对象名称
    required: true
    type: STRING
  customVariables:
  - name: host
    description: 此服务监听的域名，可以监听多个域名，也可以用 * 号通配
    required: true
    type: STRING
  - name: https
    description: https 访问设置
    required: true
    type: OBJECT
  - name: paths
    description: 此服务监听的规则
    required: true
    type: OBJECT_ARRAY
  traitDefinition:
    kube:
      template: "#运维插件的定义\n#假设运维插件的 id 和 name 都是 nginx-ingress\napiVersion: networking.k8s.io/v1\n\
        kind: Ingress\nmetadata:\n  name: {{.name}}-ingress\n  namespace: {{.namespace}}\n\
        spec:\n  ingressClassName: nginx\n  {{- if .https.enable}}\n  tls:\n    -\
        \ hosts:\n      - {{.host|quote}}\n      secretName: {{ .https.tls}}\n  {{-\
        \ end}}\n  rules:\n  - host: {{.host|quote}}\n    http:\n      paths:\n  \
        \   {{- range .paths}}\n      - path: {{.path}} \n        pathType: {{.path_type}}\n\
        \        backend:\n          service:\n            name: {{$.name}}\n    \
        \        port:\n              number: {{.port}}\n     {{- end}}"
